name: pull-request-workflow
on: pull_request #pull request가 발생했을 때 트리거가 된다.

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world pull request
      - name: step2
        run: |
          echo hello github
          echo hello daejinoh