name: push-workflow
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello github
          echo hello daejinoh.5
      - name: step3
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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